[package]
name = "d5"
version = "0.1.0"
authors = ["jmeyer <joshua.meyer@metalbackgorilla.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
